from io import BytesIO
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt

class ExportService:
    def gen_docx(self, t: str, d: dict):
        doc = Document()
        doc.add_heading(t, 0)
        
        for s in d.get("sections", []):
            doc.add_heading(s.get("title", "Section"), level=1)
            doc.add_paragraph(s.get("content", ""))
            
            if s.get("comment"):
                p = doc.add_paragraph(f"Note: {s['comment']}")
                p.style = "Intense Quote"

        f = BytesIO()
        doc.save(f)
        f.seek(0)
        return f

    def gen_pptx(self, t: str, d: dict):
        prs = Presentation()
        
        l = prs.slide_layouts[0]
        s = prs.slides.add_slide(l)
        s.shapes.title.text = t
        s.placeholders[1].text = "Generated by DraftEngine"

        l = prs.slide_layouts[1]
        for sec in d.get("sections", []):
            s = prs.slides.add_slide(l)
            s.shapes.title.text = sec.get("title", "Slide")
            
            tf = s.placeholders[1].text_frame
            tf.text = sec.get("content", "")
            
            if sec.get("comment"):
                tb = s.shapes.add_textbox(Inches(0.5), Inches(6.5), Inches(9), Inches(0.5))
                p = tb.text_frame.add_paragraph()
                p.text = f"Note: {sec['comment']}"
                p.font.size = Pt(10)
                p.font.italic = True

        f = BytesIO()
        prs.save(f)
        f.seek(0)
        return f